import { GoogleGenAI } from '@google/genai';
import RateLimitManager from './RateLimitManager.js';

export default class GeminiExtractionService {
  static getMockResponse() {
    return {
      full_name: "Jane Doe",
      company: "Acme Corp",
      designation: "Chief Executive Officer",
      email: "jane.doe@acmecorp.com",
      phone: "+1 555 123 4567",
      alternate_phone: "",
      website: "acmecorp.com",
      address: "123 Acme Way, Suite 100",
      city: "San Francisco",
      state: "CA",
      country: "US",
      notes: "Mock data generated by Gemini Mock Mode.",
      confidence_score: 0.99,
      needs_manual_review: false,
      uncertain_fields: []
    };
  }

  static async extractFromImage(cloudinaryUrl, model = null) {
    const isEnabled = process.env.GEMINI_ENABLED === 'true';
    const isMock = process.env.GEMINI_MOCK_MODE === 'true';
    const selectedModel = model || process.env.GEMINI_DEFAULT_MODEL || 'gemini-3.1-flash-lite';

    if (!isEnabled || isMock) {
      console.log(`[GeminiExtractionService] Using MOCK response for model ${selectedModel}`);
      // Simulate slight network delay
      await new Promise(resolve => setTimeout(resolve, 1500));
      return { raw: JSON.stringify(this.getMockResponse()), model: selectedModel, mocked: true };
    }

    const limitCheck = await RateLimitManager.checkLimit(selectedModel);
    if (!limitCheck.allowed) {
      throw new Error(`Rate limit exceeded: ${limitCheck.reason}`);
    }

    // Fetch the image from Cloudinary to send as base64 to Gemini
    let base64Image;
    try {
      const imgRes = await fetch(cloudinaryUrl);
      if (!imgRes.ok) throw new Error("Failed to fetch image from Cloudinary");
      const buffer = await imgRes.arrayBuffer();
      base64Image = Buffer.from(buffer).toString('base64');
    } catch (err) {
      console.error("[GeminiExtractionService] Image fetch error:", err);
      throw new Error("Unable to download image for extraction");
    }

    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
    
    const prompt = `You are extracting CRM-ready contact information from a business card image.

Rules:
* Return only valid JSON.
* Do not include markdown.
* Do not include explanation.
* Do not invent missing fields.
* If a field is not visible or uncertain, leave it as an empty string.
* Add uncertain fields to uncertain_fields.
* Normalize email to lowercase.
* Normalize website if visible.
* Normalize phone numbers where possible.
* If name, phone, or email is unclear, set needs_manual_review to true.
* Set confidence_score between 0 and 1.

Required JSON schema:
{
  "full_name": "",
  "company": "",
  "designation": "",
  "email": "",
  "phone": "",
  "alternate_phone": "",
  "website": "",
  "address": "",
  "city": "",
  "state": "",
  "country": "",
  "notes": "",
  "confidence_score": 0.0,
  "needs_manual_review": true,
  "uncertain_fields": []
}

Return only this JSON object.`;

    console.log(`[GeminiExtractionService] Calling Gemini API (${selectedModel})...`);
    
    const response = await ai.models.generateContent({
      model: selectedModel,
      contents: [
        {
          role: 'user',
          parts: [
            { text: prompt },
            {
              inlineData: {
                data: base64Image,
                mimeType: 'image/jpeg' // Assuming jpeg/png, gemini handles both via mimeType image/jpeg usually if we don't know exactly
              }
            }
          ]
        }
      ],
      config: {
        temperature: 0.1,
        responseMimeType: "application/json"
      }
    });

    const rawText = response.text;
    
    // Estimate tokens (roughly 1 token per 4 chars + base image tokens)
    const estimatedTokens = Math.ceil(prompt.length / 4) + 258 + Math.ceil(rawText.length / 4);
    await RateLimitManager.recordUsage(selectedModel, estimatedTokens);

    return { raw: rawText, model: selectedModel, mocked: false };
  }
}
